export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Beverage a DAY",
  headline: "keeps bad mood away",
  description: "來點飲料吧！",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg1.svg").default,
  alt: "HavingFun",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "store",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "好多好多飲料在這裡",
  headline: "Beverage a DAY",
  description: "今天要喝什麼呢？",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/image_refreshing_ncum.svg").default,
  alt: "image_hot_beverage",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "order",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "beverage",
  headline: "Your Order",
  description: "感謝使用 Beverage，美好的一天從 Beverage 開始！",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/image_cup_of_tea_6nqg.svg").default,
  alt: "image_cup_of_tea",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "還沒辦帳號嗎？",
  headline: "SIGN UP",
  description: "趕緊註冊開啟美好的一天",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/image_hot_beverage_2vw3.svg").default,
  alt: "image_hot_beverage",
  dark: false,
  primary: false,
  darkText: true,
};
